# Generated by Django 4.2.13 on 2024-05-26 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
